import Head from "next/head";
import styled from "@emotion/styled/macro";
import tw from "twin.macro";
import Layout from "../components/auth/Layout";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout></Layout>
        </>
    );
}
